services:
  webs:
    image: olaranmmy/actionsclass:latest
    ports:
    - 1234:80

  sonarqube:
    image: sonarqube:community
    ports:
    - 9000:9000
    depends_on:
      - webs

  sonarScan:
    image: sonarsource/sonar-scanner-cli
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_TOKEN=sqp_fd00ceddff19aa8556b5e26b3ee4c178df62d632
    depends_on:
      - sonarqube



    
